//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_jumpNrun : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean jump
        {
            get
            {
                return SteamVR_Actions.jumpNrun_jump;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grab_Pinch
        {
            get
            {
                return SteamVR_Actions.jumpNrun_Grab_Pinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean Interact_With_UI
        {
            get
            {
                return SteamVR_Actions.jumpNrun_Interact_With_UI;
            }
        }
        
        public virtual SteamVR_Action_Boolean smash
        {
            get
            {
                return SteamVR_Actions.jumpNrun_smash;
            }
        }
        
        public virtual SteamVR_Action_Boolean ActivateMenu
        {
            get
            {
                return SteamVR_Actions.jumpNrun_ActivateMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean Select
        {
            get
            {
                return SteamVR_Actions.jumpNrun_Select;
            }
        }
        
        public virtual SteamVR_Action_Vector2 MenuSelectionPosition
        {
            get
            {
                return SteamVR_Actions.jumpNrun_MenuSelectionPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean SpeedBooster
        {
            get
            {
                return SteamVR_Actions.jumpNrun_SpeedBooster;
            }
        }
    }
}
